apiVersion: apps/v1
kind: Deployment
metadata:
  name: jammers-web
spec:
  replicas: 1
  template:
    spec:
      imagePullSecrets:
        - name: ghcr-registry
      containers:
        - name: app
          imagePullPolicy: Always
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: jammers-web-db
                  key: DATABASE_URL
