apiVersion: batch/v1
kind: Job
metadata:
  name: jammers-web-migrate
spec:
  template:
    spec:
      imagePullSecrets:
        - name: ghcr-registry
      restartPolicy: Never
      containers:
        - name: migrate
          image: ghcr.io/kinteus/jammers-web:latest
          command: ["sh", "-c", "npx prisma migrate deploy"]
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 100m
              memory: 256Mi
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: jammers-web-db
                  key: DATABASE_URL
          envFrom:
            - configMapRef:
                name: jammers-web-config
            - secretRef:
                name: jammers-web-secrets
