apiVersion: batch/v1
kind: Job
metadata:
  name: jammers-web-migrate
  labels:
    app.kubernetes.io/name: jammers-web
    app.kubernetes.io/component: jammers-web-migration
spec:
  backoffLimit: 0
  activeDeadlineSeconds: 900
  ttlSecondsAfterFinished: 86400
  template:
    metadata:
      labels:
        app.kubernetes.io/name: jammers-web
        app.kubernetes.io/component: jammers-web-migration
    spec:
      imagePullSecrets:
        - name: ghcr-registry
      restartPolicy: Never
      containers:
        - name: migrate
          image: ghcr.io/kinteus/jammers-web:latest
          command: ["sh", "-c", "npx prisma migrate deploy"]
          resources:
            requests:
              cpu: 50m
              memory: 256Mi
            limits:
              cpu: 100m
              memory: 768Mi
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: jammers-web-db
                  key: DATABASE_URL
          envFrom:
            - configMapRef:
                name: jammers-web-config
            - secretRef:
                name: jammers-web-secrets
